// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SoVelSYHhZUMrkNMaoZpGTKash0GNXA',
    appId: '1:527109492721:web:5eb1d7a2f7dcecd4d8be50',
    messagingSenderId: '527109492721',
    projectId: 'bartender-9acb1',
    authDomain: 'bartender-9acb1.firebaseapp.com',
    storageBucket: 'bartender-9acb1.firebasestorage.app',
    measurementId: 'G-P7CY5ZDL54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0ARO2Acxus9a99FsSOQ0t2saC3jsgus',
    appId: '1:527109492721:android:a9f64f5d8f3fe793d8be50',
    messagingSenderId: '527109492721',
    projectId: 'bartender-9acb1',
    storageBucket: 'bartender-9acb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznt1XNYS3v9fcacCYZOKk2mTor5roTSQ',
    appId: '1:527109492721:ios:3876fbd8196c0f71d8be50',
    messagingSenderId: '527109492721',
    projectId: 'bartender-9acb1',
    storageBucket: 'bartender-9acb1.firebasestorage.app',
    iosBundleId: 'com.example.bartender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDznt1XNYS3v9fcacCYZOKk2mTor5roTSQ',
    appId: '1:527109492721:ios:3876fbd8196c0f71d8be50',
    messagingSenderId: '527109492721',
    projectId: 'bartender-9acb1',
    storageBucket: 'bartender-9acb1.firebasestorage.app',
    iosBundleId: 'com.example.bartender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2SoVelSYHhZUMrkNMaoZpGTKash0GNXA',
    appId: '1:527109492721:web:531c88633f843de5d8be50',
    messagingSenderId: '527109492721',
    projectId: 'bartender-9acb1',
    authDomain: 'bartender-9acb1.firebaseapp.com',
    storageBucket: 'bartender-9acb1.firebasestorage.app',
    measurementId: 'G-6DEKEMEKT3',
  );
}
